//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiceMill_MVC.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageHeader", Namespace="http://api.onnorokomsms.com/")]
    [System.SerializableAttribute()]
    public partial class MessageHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarskTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampingNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserPassword {
            get {
                return this.UserPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPasswordField, value) != true)) {
                    this.UserPasswordField = value;
                    this.RaisePropertyChanged("UserPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MarskText {
            get {
                return this.MarskTextField;
            }
            set {
                if ((object.ReferenceEquals(this.MarskTextField, value) != true)) {
                    this.MarskTextField = value;
                    this.RaisePropertyChanged("MarskText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CampingName {
            get {
                return this.CampingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CampingNameField, value) != true)) {
                    this.CampingNameField = value;
                    this.RaisePropertyChanged("CampingName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WsSms", Namespace="http://api.onnorokomsms.com/")]
    [System.SerializableAttribute()]
    public partial class WsSms : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MobileNumber {
            get {
                return this.MobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNumberField, value) != true)) {
                    this.MobileNumberField = value;
                    this.RaisePropertyChanged("MobileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SmsText {
            get {
                return this.SmsTextField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsTextField, value) != true)) {
                    this.SmsTextField = value;
                    this.RaisePropertyChanged("SmsText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://api.onnorokomsms.com/", ConfigurationName="ServiceReference1.SendSmsSoap")]
    public interface SendSmsSoap {
        
        // CODEGEN: Generating message contract since element name messageHeader from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/OneToOneBulk", ReplyAction="*")]
        RiceMill_MVC.ServiceReference1.OneToOneBulkResponse OneToOneBulk(RiceMill_MVC.ServiceReference1.OneToOneBulkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/OneToOneBulk", ReplyAction="*")]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.OneToOneBulkResponse> OneToOneBulkAsync(RiceMill_MVC.ServiceReference1.OneToOneBulkRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/OneToOne", ReplyAction="*")]
        RiceMill_MVC.ServiceReference1.OneToOneResponse OneToOne(RiceMill_MVC.ServiceReference1.OneToOneRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/OneToOne", ReplyAction="*")]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.OneToOneResponse> OneToOneAsync(RiceMill_MVC.ServiceReference1.OneToOneRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/OneToMany", ReplyAction="*")]
        RiceMill_MVC.ServiceReference1.OneToManyResponse OneToMany(RiceMill_MVC.ServiceReference1.OneToManyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/OneToMany", ReplyAction="*")]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.OneToManyResponse> OneToManyAsync(RiceMill_MVC.ServiceReference1.OneToManyRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/DeliveryStatus", ReplyAction="*")]
        RiceMill_MVC.ServiceReference1.DeliveryStatusResponse DeliveryStatus(RiceMill_MVC.ServiceReference1.DeliveryStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/DeliveryStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.DeliveryStatusResponse> DeliveryStatusAsync(RiceMill_MVC.ServiceReference1.DeliveryStatusRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetBalance", ReplyAction="*")]
        RiceMill_MVC.ServiceReference1.GetBalanceResponse GetBalance(RiceMill_MVC.ServiceReference1.GetBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.GetBalanceResponse> GetBalanceAsync(RiceMill_MVC.ServiceReference1.GetBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetMask", ReplyAction="*")]
        RiceMill_MVC.ServiceReference1.GetMaskResponse GetMask(RiceMill_MVC.ServiceReference1.GetMaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetMask", ReplyAction="*")]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.GetMaskResponse> GetMaskAsync(RiceMill_MVC.ServiceReference1.GetMaskRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/NumberSms", ReplyAction="*")]
        RiceMill_MVC.ServiceReference1.NumberSmsResponse NumberSms(RiceMill_MVC.ServiceReference1.NumberSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/NumberSms", ReplyAction="*")]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.NumberSmsResponse> NumberSmsAsync(RiceMill_MVC.ServiceReference1.NumberSmsRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/ListSms", ReplyAction="*")]
        RiceMill_MVC.ServiceReference1.ListSmsResponse ListSms(RiceMill_MVC.ServiceReference1.ListSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/ListSms", ReplyAction="*")]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.ListSmsResponse> ListSmsAsync(RiceMill_MVC.ServiceReference1.ListSmsRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/SMSDeliveryStatus", ReplyAction="*")]
        RiceMill_MVC.ServiceReference1.SMSDeliveryStatusResponse SMSDeliveryStatus(RiceMill_MVC.ServiceReference1.SMSDeliveryStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/SMSDeliveryStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.SMSDeliveryStatusResponse> SMSDeliveryStatusAsync(RiceMill_MVC.ServiceReference1.SMSDeliveryStatusRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetCurrentBalance", ReplyAction="*")]
        RiceMill_MVC.ServiceReference1.GetCurrentBalanceResponse GetCurrentBalance(RiceMill_MVC.ServiceReference1.GetCurrentBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetCurrentBalance", ReplyAction="*")]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.GetCurrentBalanceResponse> GetCurrentBalanceAsync(RiceMill_MVC.ServiceReference1.GetCurrentBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name apiKey from namespace http://api.onnorokomsms.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetAllMask", ReplyAction="*")]
        RiceMill_MVC.ServiceReference1.GetAllMaskResponse GetAllMask(RiceMill_MVC.ServiceReference1.GetAllMaskRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://api.onnorokomsms.com/GetAllMask", ReplyAction="*")]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.GetAllMaskResponse> GetAllMaskAsync(RiceMill_MVC.ServiceReference1.GetAllMaskRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OneToOneBulkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OneToOneBulk", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.OneToOneBulkRequestBody Body;
        
        public OneToOneBulkRequest() {
        }
        
        public OneToOneBulkRequest(RiceMill_MVC.ServiceReference1.OneToOneBulkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class OneToOneBulkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public RiceMill_MVC.ServiceReference1.MessageHeader messageHeader;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public RiceMill_MVC.ServiceReference1.WsSms[] wsSmses;
        
        public OneToOneBulkRequestBody() {
        }
        
        public OneToOneBulkRequestBody(RiceMill_MVC.ServiceReference1.MessageHeader messageHeader, RiceMill_MVC.ServiceReference1.WsSms[] wsSmses) {
            this.messageHeader = messageHeader;
            this.wsSmses = wsSmses;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OneToOneBulkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OneToOneBulkResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.OneToOneBulkResponseBody Body;
        
        public OneToOneBulkResponse() {
        }
        
        public OneToOneBulkResponse(RiceMill_MVC.ServiceReference1.OneToOneBulkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class OneToOneBulkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OneToOneBulkResult;
        
        public OneToOneBulkResponseBody() {
        }
        
        public OneToOneBulkResponseBody(string OneToOneBulkResult) {
            this.OneToOneBulkResult = OneToOneBulkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OneToOneRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OneToOne", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.OneToOneRequestBody Body;
        
        public OneToOneRequest() {
        }
        
        public OneToOneRequest(RiceMill_MVC.ServiceReference1.OneToOneRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class OneToOneRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string mobileNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string smsText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string type;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string maskName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string campaignName;
        
        public OneToOneRequestBody() {
        }
        
        public OneToOneRequestBody(string userName, string userPassword, string mobileNumber, string smsText, string type, string maskName, string campaignName) {
            this.userName = userName;
            this.userPassword = userPassword;
            this.mobileNumber = mobileNumber;
            this.smsText = smsText;
            this.type = type;
            this.maskName = maskName;
            this.campaignName = campaignName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OneToOneResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OneToOneResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.OneToOneResponseBody Body;
        
        public OneToOneResponse() {
        }
        
        public OneToOneResponse(RiceMill_MVC.ServiceReference1.OneToOneResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class OneToOneResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OneToOneResult;
        
        public OneToOneResponseBody() {
        }
        
        public OneToOneResponseBody(string OneToOneResult) {
            this.OneToOneResult = OneToOneResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OneToManyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OneToMany", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.OneToManyRequestBody Body;
        
        public OneToManyRequest() {
        }
        
        public OneToManyRequest(RiceMill_MVC.ServiceReference1.OneToManyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class OneToManyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string messageText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string numberList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string smsType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string maskName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string campaignName;
        
        public OneToManyRequestBody() {
        }
        
        public OneToManyRequestBody(string userName, string userPassword, string messageText, string numberList, string smsType, string maskName, string campaignName) {
            this.userName = userName;
            this.userPassword = userPassword;
            this.messageText = messageText;
            this.numberList = numberList;
            this.smsType = smsType;
            this.maskName = maskName;
            this.campaignName = campaignName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OneToManyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OneToManyResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.OneToManyResponseBody Body;
        
        public OneToManyResponse() {
        }
        
        public OneToManyResponse(RiceMill_MVC.ServiceReference1.OneToManyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class OneToManyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OneToManyResult;
        
        public OneToManyResponseBody() {
        }
        
        public OneToManyResponseBody(string OneToManyResult) {
            this.OneToManyResult = OneToManyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeliveryStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeliveryStatus", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.DeliveryStatusRequestBody Body;
        
        public DeliveryStatusRequest() {
        }
        
        public DeliveryStatusRequest(RiceMill_MVC.ServiceReference1.DeliveryStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class DeliveryStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string responseId;
        
        public DeliveryStatusRequestBody() {
        }
        
        public DeliveryStatusRequestBody(string userName, string userPassword, string responseId) {
            this.userName = userName;
            this.userPassword = userPassword;
            this.responseId = responseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeliveryStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeliveryStatusResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.DeliveryStatusResponseBody Body;
        
        public DeliveryStatusResponse() {
        }
        
        public DeliveryStatusResponse(RiceMill_MVC.ServiceReference1.DeliveryStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class DeliveryStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeliveryStatusResult;
        
        public DeliveryStatusResponseBody() {
        }
        
        public DeliveryStatusResponseBody(string DeliveryStatusResult) {
            this.DeliveryStatusResult = DeliveryStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalance", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.GetBalanceRequestBody Body;
        
        public GetBalanceRequest() {
        }
        
        public GetBalanceRequest(RiceMill_MVC.ServiceReference1.GetBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        public GetBalanceRequestBody() {
        }
        
        public GetBalanceRequestBody(string userName, string userPassword) {
            this.userName = userName;
            this.userPassword = userPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalanceResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.GetBalanceResponseBody Body;
        
        public GetBalanceResponse() {
        }
        
        public GetBalanceResponse(RiceMill_MVC.ServiceReference1.GetBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetBalanceResult;
        
        public GetBalanceResponseBody() {
        }
        
        public GetBalanceResponseBody(string GetBalanceResult) {
            this.GetBalanceResult = GetBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMask", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.GetMaskRequestBody Body;
        
        public GetMaskRequest() {
        }
        
        public GetMaskRequest(RiceMill_MVC.ServiceReference1.GetMaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetMaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userPassword;
        
        public GetMaskRequestBody() {
        }
        
        public GetMaskRequestBody(string userName, string userPassword) {
            this.userName = userName;
            this.userPassword = userPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMaskResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.GetMaskResponseBody Body;
        
        public GetMaskResponse() {
        }
        
        public GetMaskResponse(RiceMill_MVC.ServiceReference1.GetMaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetMaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetMaskResult;
        
        public GetMaskResponseBody() {
        }
        
        public GetMaskResponseBody(string GetMaskResult) {
            this.GetMaskResult = GetMaskResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberSms", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.NumberSmsRequestBody Body;
        
        public NumberSmsRequest() {
        }
        
        public NumberSmsRequest(RiceMill_MVC.ServiceReference1.NumberSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class NumberSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string messageText;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string numberList;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string smsType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string maskName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string campaignName;
        
        public NumberSmsRequestBody() {
        }
        
        public NumberSmsRequestBody(string apiKey, string messageText, string numberList, string smsType, string maskName, string campaignName) {
            this.apiKey = apiKey;
            this.messageText = messageText;
            this.numberList = numberList;
            this.smsType = smsType;
            this.maskName = maskName;
            this.campaignName = campaignName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NumberSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NumberSmsResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.NumberSmsResponseBody Body;
        
        public NumberSmsResponse() {
        }
        
        public NumberSmsResponse(RiceMill_MVC.ServiceReference1.NumberSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class NumberSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NumberSmsResult;
        
        public NumberSmsResponseBody() {
        }
        
        public NumberSmsResponseBody(string NumberSmsResult) {
            this.NumberSmsResult = NumberSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListSmsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListSms", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.ListSmsRequestBody Body;
        
        public ListSmsRequest() {
        }
        
        public ListSmsRequest(RiceMill_MVC.ServiceReference1.ListSmsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class ListSmsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public RiceMill_MVC.ServiceReference1.WsSms[] wsSmses;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string maskName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string campaignName;
        
        public ListSmsRequestBody() {
        }
        
        public ListSmsRequestBody(string apiKey, RiceMill_MVC.ServiceReference1.WsSms[] wsSmses, string maskName, string campaignName) {
            this.apiKey = apiKey;
            this.wsSmses = wsSmses;
            this.maskName = maskName;
            this.campaignName = campaignName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListSmsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListSmsResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.ListSmsResponseBody Body;
        
        public ListSmsResponse() {
        }
        
        public ListSmsResponse(RiceMill_MVC.ServiceReference1.ListSmsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class ListSmsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ListSmsResult;
        
        public ListSmsResponseBody() {
        }
        
        public ListSmsResponseBody(string ListSmsResult) {
            this.ListSmsResult = ListSmsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMSDeliveryStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMSDeliveryStatus", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.SMSDeliveryStatusRequestBody Body;
        
        public SMSDeliveryStatusRequest() {
        }
        
        public SMSDeliveryStatusRequest(RiceMill_MVC.ServiceReference1.SMSDeliveryStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class SMSDeliveryStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string responseId;
        
        public SMSDeliveryStatusRequestBody() {
        }
        
        public SMSDeliveryStatusRequestBody(string apiKey, string responseId) {
            this.apiKey = apiKey;
            this.responseId = responseId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SMSDeliveryStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SMSDeliveryStatusResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.SMSDeliveryStatusResponseBody Body;
        
        public SMSDeliveryStatusResponse() {
        }
        
        public SMSDeliveryStatusResponse(RiceMill_MVC.ServiceReference1.SMSDeliveryStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class SMSDeliveryStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SMSDeliveryStatusResult;
        
        public SMSDeliveryStatusResponseBody() {
        }
        
        public SMSDeliveryStatusResponseBody(string SMSDeliveryStatusResult) {
            this.SMSDeliveryStatusResult = SMSDeliveryStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentBalance", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.GetCurrentBalanceRequestBody Body;
        
        public GetCurrentBalanceRequest() {
        }
        
        public GetCurrentBalanceRequest(RiceMill_MVC.ServiceReference1.GetCurrentBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetCurrentBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        public GetCurrentBalanceRequestBody() {
        }
        
        public GetCurrentBalanceRequestBody(string apiKey) {
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentBalanceResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.GetCurrentBalanceResponseBody Body;
        
        public GetCurrentBalanceResponse() {
        }
        
        public GetCurrentBalanceResponse(RiceMill_MVC.ServiceReference1.GetCurrentBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetCurrentBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrentBalanceResult;
        
        public GetCurrentBalanceResponseBody() {
        }
        
        public GetCurrentBalanceResponseBody(string GetCurrentBalanceResult) {
            this.GetCurrentBalanceResult = GetCurrentBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMaskRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMask", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.GetAllMaskRequestBody Body;
        
        public GetAllMaskRequest() {
        }
        
        public GetAllMaskRequest(RiceMill_MVC.ServiceReference1.GetAllMaskRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetAllMaskRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string apiKey;
        
        public GetAllMaskRequestBody() {
        }
        
        public GetAllMaskRequestBody(string apiKey) {
            this.apiKey = apiKey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMaskResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMaskResponse", Namespace="http://api.onnorokomsms.com/", Order=0)]
        public RiceMill_MVC.ServiceReference1.GetAllMaskResponseBody Body;
        
        public GetAllMaskResponse() {
        }
        
        public GetAllMaskResponse(RiceMill_MVC.ServiceReference1.GetAllMaskResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.onnorokomsms.com/")]
    public partial class GetAllMaskResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllMaskResult;
        
        public GetAllMaskResponseBody() {
        }
        
        public GetAllMaskResponseBody(string GetAllMaskResult) {
            this.GetAllMaskResult = GetAllMaskResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSmsSoapChannel : RiceMill_MVC.ServiceReference1.SendSmsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSmsSoapClient : System.ServiceModel.ClientBase<RiceMill_MVC.ServiceReference1.SendSmsSoap>, RiceMill_MVC.ServiceReference1.SendSmsSoap {
        
        public SendSmsSoapClient() {
        }
        
        public SendSmsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSmsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSmsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSmsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RiceMill_MVC.ServiceReference1.OneToOneBulkResponse RiceMill_MVC.ServiceReference1.SendSmsSoap.OneToOneBulk(RiceMill_MVC.ServiceReference1.OneToOneBulkRequest request) {
            return base.Channel.OneToOneBulk(request);
        }
        
        public string OneToOneBulk(RiceMill_MVC.ServiceReference1.MessageHeader messageHeader, RiceMill_MVC.ServiceReference1.WsSms[] wsSmses) {
            RiceMill_MVC.ServiceReference1.OneToOneBulkRequest inValue = new RiceMill_MVC.ServiceReference1.OneToOneBulkRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.OneToOneBulkRequestBody();
            inValue.Body.messageHeader = messageHeader;
            inValue.Body.wsSmses = wsSmses;
            RiceMill_MVC.ServiceReference1.OneToOneBulkResponse retVal = ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).OneToOneBulk(inValue);
            return retVal.Body.OneToOneBulkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.OneToOneBulkResponse> RiceMill_MVC.ServiceReference1.SendSmsSoap.OneToOneBulkAsync(RiceMill_MVC.ServiceReference1.OneToOneBulkRequest request) {
            return base.Channel.OneToOneBulkAsync(request);
        }
        
        public System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.OneToOneBulkResponse> OneToOneBulkAsync(RiceMill_MVC.ServiceReference1.MessageHeader messageHeader, RiceMill_MVC.ServiceReference1.WsSms[] wsSmses) {
            RiceMill_MVC.ServiceReference1.OneToOneBulkRequest inValue = new RiceMill_MVC.ServiceReference1.OneToOneBulkRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.OneToOneBulkRequestBody();
            inValue.Body.messageHeader = messageHeader;
            inValue.Body.wsSmses = wsSmses;
            return ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).OneToOneBulkAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RiceMill_MVC.ServiceReference1.OneToOneResponse RiceMill_MVC.ServiceReference1.SendSmsSoap.OneToOne(RiceMill_MVC.ServiceReference1.OneToOneRequest request) {
            return base.Channel.OneToOne(request);
        }
        
        public string OneToOne(string userName, string userPassword, string mobileNumber, string smsText, string type, string maskName, string campaignName) {
            RiceMill_MVC.ServiceReference1.OneToOneRequest inValue = new RiceMill_MVC.ServiceReference1.OneToOneRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.OneToOneRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.mobileNumber = mobileNumber;
            inValue.Body.smsText = smsText;
            inValue.Body.type = type;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            RiceMill_MVC.ServiceReference1.OneToOneResponse retVal = ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).OneToOne(inValue);
            return retVal.Body.OneToOneResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.OneToOneResponse> RiceMill_MVC.ServiceReference1.SendSmsSoap.OneToOneAsync(RiceMill_MVC.ServiceReference1.OneToOneRequest request) {
            return base.Channel.OneToOneAsync(request);
        }
        
        public System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.OneToOneResponse> OneToOneAsync(string userName, string userPassword, string mobileNumber, string smsText, string type, string maskName, string campaignName) {
            RiceMill_MVC.ServiceReference1.OneToOneRequest inValue = new RiceMill_MVC.ServiceReference1.OneToOneRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.OneToOneRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.mobileNumber = mobileNumber;
            inValue.Body.smsText = smsText;
            inValue.Body.type = type;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            return ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).OneToOneAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RiceMill_MVC.ServiceReference1.OneToManyResponse RiceMill_MVC.ServiceReference1.SendSmsSoap.OneToMany(RiceMill_MVC.ServiceReference1.OneToManyRequest request) {
            return base.Channel.OneToMany(request);
        }
        
        public string OneToMany(string userName, string userPassword, string messageText, string numberList, string smsType, string maskName, string campaignName) {
            RiceMill_MVC.ServiceReference1.OneToManyRequest inValue = new RiceMill_MVC.ServiceReference1.OneToManyRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.OneToManyRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.messageText = messageText;
            inValue.Body.numberList = numberList;
            inValue.Body.smsType = smsType;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            RiceMill_MVC.ServiceReference1.OneToManyResponse retVal = ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).OneToMany(inValue);
            return retVal.Body.OneToManyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.OneToManyResponse> RiceMill_MVC.ServiceReference1.SendSmsSoap.OneToManyAsync(RiceMill_MVC.ServiceReference1.OneToManyRequest request) {
            return base.Channel.OneToManyAsync(request);
        }
        
        public System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.OneToManyResponse> OneToManyAsync(string userName, string userPassword, string messageText, string numberList, string smsType, string maskName, string campaignName) {
            RiceMill_MVC.ServiceReference1.OneToManyRequest inValue = new RiceMill_MVC.ServiceReference1.OneToManyRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.OneToManyRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.messageText = messageText;
            inValue.Body.numberList = numberList;
            inValue.Body.smsType = smsType;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            return ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).OneToManyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RiceMill_MVC.ServiceReference1.DeliveryStatusResponse RiceMill_MVC.ServiceReference1.SendSmsSoap.DeliveryStatus(RiceMill_MVC.ServiceReference1.DeliveryStatusRequest request) {
            return base.Channel.DeliveryStatus(request);
        }
        
        public string DeliveryStatus(string userName, string userPassword, string responseId) {
            RiceMill_MVC.ServiceReference1.DeliveryStatusRequest inValue = new RiceMill_MVC.ServiceReference1.DeliveryStatusRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.DeliveryStatusRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.responseId = responseId;
            RiceMill_MVC.ServiceReference1.DeliveryStatusResponse retVal = ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).DeliveryStatus(inValue);
            return retVal.Body.DeliveryStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.DeliveryStatusResponse> RiceMill_MVC.ServiceReference1.SendSmsSoap.DeliveryStatusAsync(RiceMill_MVC.ServiceReference1.DeliveryStatusRequest request) {
            return base.Channel.DeliveryStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.DeliveryStatusResponse> DeliveryStatusAsync(string userName, string userPassword, string responseId) {
            RiceMill_MVC.ServiceReference1.DeliveryStatusRequest inValue = new RiceMill_MVC.ServiceReference1.DeliveryStatusRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.DeliveryStatusRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            inValue.Body.responseId = responseId;
            return ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).DeliveryStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RiceMill_MVC.ServiceReference1.GetBalanceResponse RiceMill_MVC.ServiceReference1.SendSmsSoap.GetBalance(RiceMill_MVC.ServiceReference1.GetBalanceRequest request) {
            return base.Channel.GetBalance(request);
        }
        
        public string GetBalance(string userName, string userPassword) {
            RiceMill_MVC.ServiceReference1.GetBalanceRequest inValue = new RiceMill_MVC.ServiceReference1.GetBalanceRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.GetBalanceRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            RiceMill_MVC.ServiceReference1.GetBalanceResponse retVal = ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).GetBalance(inValue);
            return retVal.Body.GetBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.GetBalanceResponse> RiceMill_MVC.ServiceReference1.SendSmsSoap.GetBalanceAsync(RiceMill_MVC.ServiceReference1.GetBalanceRequest request) {
            return base.Channel.GetBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.GetBalanceResponse> GetBalanceAsync(string userName, string userPassword) {
            RiceMill_MVC.ServiceReference1.GetBalanceRequest inValue = new RiceMill_MVC.ServiceReference1.GetBalanceRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.GetBalanceRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            return ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).GetBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RiceMill_MVC.ServiceReference1.GetMaskResponse RiceMill_MVC.ServiceReference1.SendSmsSoap.GetMask(RiceMill_MVC.ServiceReference1.GetMaskRequest request) {
            return base.Channel.GetMask(request);
        }
        
        public string GetMask(string userName, string userPassword) {
            RiceMill_MVC.ServiceReference1.GetMaskRequest inValue = new RiceMill_MVC.ServiceReference1.GetMaskRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.GetMaskRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            RiceMill_MVC.ServiceReference1.GetMaskResponse retVal = ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).GetMask(inValue);
            return retVal.Body.GetMaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.GetMaskResponse> RiceMill_MVC.ServiceReference1.SendSmsSoap.GetMaskAsync(RiceMill_MVC.ServiceReference1.GetMaskRequest request) {
            return base.Channel.GetMaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.GetMaskResponse> GetMaskAsync(string userName, string userPassword) {
            RiceMill_MVC.ServiceReference1.GetMaskRequest inValue = new RiceMill_MVC.ServiceReference1.GetMaskRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.GetMaskRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.userPassword = userPassword;
            return ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).GetMaskAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RiceMill_MVC.ServiceReference1.NumberSmsResponse RiceMill_MVC.ServiceReference1.SendSmsSoap.NumberSms(RiceMill_MVC.ServiceReference1.NumberSmsRequest request) {
            return base.Channel.NumberSms(request);
        }
        
        public string NumberSms(string apiKey, string messageText, string numberList, string smsType, string maskName, string campaignName) {
            RiceMill_MVC.ServiceReference1.NumberSmsRequest inValue = new RiceMill_MVC.ServiceReference1.NumberSmsRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.NumberSmsRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.messageText = messageText;
            inValue.Body.numberList = numberList;
            inValue.Body.smsType = smsType;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            RiceMill_MVC.ServiceReference1.NumberSmsResponse retVal = ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).NumberSms(inValue);
            return retVal.Body.NumberSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.NumberSmsResponse> RiceMill_MVC.ServiceReference1.SendSmsSoap.NumberSmsAsync(RiceMill_MVC.ServiceReference1.NumberSmsRequest request) {
            return base.Channel.NumberSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.NumberSmsResponse> NumberSmsAsync(string apiKey, string messageText, string numberList, string smsType, string maskName, string campaignName) {
            RiceMill_MVC.ServiceReference1.NumberSmsRequest inValue = new RiceMill_MVC.ServiceReference1.NumberSmsRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.NumberSmsRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.messageText = messageText;
            inValue.Body.numberList = numberList;
            inValue.Body.smsType = smsType;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            return ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).NumberSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RiceMill_MVC.ServiceReference1.ListSmsResponse RiceMill_MVC.ServiceReference1.SendSmsSoap.ListSms(RiceMill_MVC.ServiceReference1.ListSmsRequest request) {
            return base.Channel.ListSms(request);
        }
        
        public string ListSms(string apiKey, RiceMill_MVC.ServiceReference1.WsSms[] wsSmses, string maskName, string campaignName) {
            RiceMill_MVC.ServiceReference1.ListSmsRequest inValue = new RiceMill_MVC.ServiceReference1.ListSmsRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.ListSmsRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.wsSmses = wsSmses;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            RiceMill_MVC.ServiceReference1.ListSmsResponse retVal = ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).ListSms(inValue);
            return retVal.Body.ListSmsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.ListSmsResponse> RiceMill_MVC.ServiceReference1.SendSmsSoap.ListSmsAsync(RiceMill_MVC.ServiceReference1.ListSmsRequest request) {
            return base.Channel.ListSmsAsync(request);
        }
        
        public System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.ListSmsResponse> ListSmsAsync(string apiKey, RiceMill_MVC.ServiceReference1.WsSms[] wsSmses, string maskName, string campaignName) {
            RiceMill_MVC.ServiceReference1.ListSmsRequest inValue = new RiceMill_MVC.ServiceReference1.ListSmsRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.ListSmsRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.wsSmses = wsSmses;
            inValue.Body.maskName = maskName;
            inValue.Body.campaignName = campaignName;
            return ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).ListSmsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RiceMill_MVC.ServiceReference1.SMSDeliveryStatusResponse RiceMill_MVC.ServiceReference1.SendSmsSoap.SMSDeliveryStatus(RiceMill_MVC.ServiceReference1.SMSDeliveryStatusRequest request) {
            return base.Channel.SMSDeliveryStatus(request);
        }
        
        public string SMSDeliveryStatus(string apiKey, string responseId) {
            RiceMill_MVC.ServiceReference1.SMSDeliveryStatusRequest inValue = new RiceMill_MVC.ServiceReference1.SMSDeliveryStatusRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.SMSDeliveryStatusRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.responseId = responseId;
            RiceMill_MVC.ServiceReference1.SMSDeliveryStatusResponse retVal = ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).SMSDeliveryStatus(inValue);
            return retVal.Body.SMSDeliveryStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.SMSDeliveryStatusResponse> RiceMill_MVC.ServiceReference1.SendSmsSoap.SMSDeliveryStatusAsync(RiceMill_MVC.ServiceReference1.SMSDeliveryStatusRequest request) {
            return base.Channel.SMSDeliveryStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.SMSDeliveryStatusResponse> SMSDeliveryStatusAsync(string apiKey, string responseId) {
            RiceMill_MVC.ServiceReference1.SMSDeliveryStatusRequest inValue = new RiceMill_MVC.ServiceReference1.SMSDeliveryStatusRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.SMSDeliveryStatusRequestBody();
            inValue.Body.apiKey = apiKey;
            inValue.Body.responseId = responseId;
            return ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).SMSDeliveryStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RiceMill_MVC.ServiceReference1.GetCurrentBalanceResponse RiceMill_MVC.ServiceReference1.SendSmsSoap.GetCurrentBalance(RiceMill_MVC.ServiceReference1.GetCurrentBalanceRequest request) {
            return base.Channel.GetCurrentBalance(request);
        }
        
        public string GetCurrentBalance(string apiKey) {
            RiceMill_MVC.ServiceReference1.GetCurrentBalanceRequest inValue = new RiceMill_MVC.ServiceReference1.GetCurrentBalanceRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.GetCurrentBalanceRequestBody();
            inValue.Body.apiKey = apiKey;
            RiceMill_MVC.ServiceReference1.GetCurrentBalanceResponse retVal = ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).GetCurrentBalance(inValue);
            return retVal.Body.GetCurrentBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.GetCurrentBalanceResponse> RiceMill_MVC.ServiceReference1.SendSmsSoap.GetCurrentBalanceAsync(RiceMill_MVC.ServiceReference1.GetCurrentBalanceRequest request) {
            return base.Channel.GetCurrentBalanceAsync(request);
        }
        
        public System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.GetCurrentBalanceResponse> GetCurrentBalanceAsync(string apiKey) {
            RiceMill_MVC.ServiceReference1.GetCurrentBalanceRequest inValue = new RiceMill_MVC.ServiceReference1.GetCurrentBalanceRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.GetCurrentBalanceRequestBody();
            inValue.Body.apiKey = apiKey;
            return ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).GetCurrentBalanceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RiceMill_MVC.ServiceReference1.GetAllMaskResponse RiceMill_MVC.ServiceReference1.SendSmsSoap.GetAllMask(RiceMill_MVC.ServiceReference1.GetAllMaskRequest request) {
            return base.Channel.GetAllMask(request);
        }
        
        public string GetAllMask(string apiKey) {
            RiceMill_MVC.ServiceReference1.GetAllMaskRequest inValue = new RiceMill_MVC.ServiceReference1.GetAllMaskRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.GetAllMaskRequestBody();
            inValue.Body.apiKey = apiKey;
            RiceMill_MVC.ServiceReference1.GetAllMaskResponse retVal = ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).GetAllMask(inValue);
            return retVal.Body.GetAllMaskResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.GetAllMaskResponse> RiceMill_MVC.ServiceReference1.SendSmsSoap.GetAllMaskAsync(RiceMill_MVC.ServiceReference1.GetAllMaskRequest request) {
            return base.Channel.GetAllMaskAsync(request);
        }
        
        public System.Threading.Tasks.Task<RiceMill_MVC.ServiceReference1.GetAllMaskResponse> GetAllMaskAsync(string apiKey) {
            RiceMill_MVC.ServiceReference1.GetAllMaskRequest inValue = new RiceMill_MVC.ServiceReference1.GetAllMaskRequest();
            inValue.Body = new RiceMill_MVC.ServiceReference1.GetAllMaskRequestBody();
            inValue.Body.apiKey = apiKey;
            return ((RiceMill_MVC.ServiceReference1.SendSmsSoap)(this)).GetAllMaskAsync(inValue);
        }
    }
}
