//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiceMill_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankReconciliation
    {
        public int Id { get; set; }
        public Nullable<int> LedgerPostingId { get; set; }
        public Nullable<System.DateTime> StatementDate { get; set; }
        public Nullable<System.DateTime> ExtraDate { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
    
        public virtual LedgerPosting LedgerPosting { get; set; }
    }
}
