//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiceMill_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContraMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContraMaster()
        {
            this.ContraDetails = new HashSet<ContraDetail>();
        }
    
        public int Id { get; set; }
        public string VoucherNo { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> SuffixPrefixId { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> LedgerId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Narration { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> VoucherTypeId { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
        public Nullable<System.DateTime> ExtraDate { get; set; }
        public string Extra1 { get; set; }
        public string extra2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContraDetail> ContraDetails { get; set; }
        public virtual ContraMaster ContraMaster1 { get; set; }
        public virtual ContraMaster ContraMaster2 { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual VoucherType VoucherType { get; set; }
        public virtual FinancialYear FinancialYear { get; set; }
    }
}
