//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REX_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        public string InventoryGuid { get; set; }
        public Nullable<int> QtyInBale { get; set; }
        public int SupplierId { get; set; }
        public int WarehouseId { get; set; }
        public Nullable<decimal> OpeningQty { get; set; }
        public Nullable<decimal> ReceiveQty { get; set; }
        public Nullable<decimal> AddFromOtherSource { get; set; }
        public Nullable<decimal> ProductionQty { get; set; }
        public Nullable<decimal> ReturnQty { get; set; }
        public Nullable<decimal> Faulty { get; set; }
        public Nullable<decimal> SalesQty { get; set; }
        public decimal BalanceQty { get; set; }
        public string Notes { get; set; }
        public string GoodsType { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual WareHouse WareHouse { get; set; }
    }
}
