//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiceMill_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JournalMaster
    {
        public int Id { get; set; }
        public string VoucherNo { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> SuffixPrefixId { get; set; }
        public Nullable<System.DateTime> LadgerDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Narration { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> VoucherTypeId { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<System.DateTime> ExtraDate { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
    
        public virtual FinancialYear FinancialYear { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        public virtual VoucherType VoucherType { get; set; }
    }
}
