//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REX_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyBalance
    {
        public int PartyBalanceId { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public int LedgerId { get; set; }
        public int VoucherTypeId { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<int> AgainstVoucherTypeId { get; set; }
        public string AgainstVoucherNo { get; set; }
        public string InvoiceNo { get; set; }
        public string AgainstInvoiceNo { get; set; }
        public string ReferenceType { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<int> CreditPeriod { get; set; }
        public Nullable<int> FinancialYearId { get; set; }
        public Nullable<System.DateTime> extraDate { get; set; }
        public string extra1 { get; set; }
        public string extra2 { get; set; }
    
        public virtual AccountLedger AccountLedger { get; set; }
        public virtual VoucherType VoucherType { get; set; }
    }
}
