//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiceMill_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInfo
    {
        public string SBarCode { get; set; }
        public string PBarCode { get; set; }
        public string Barcode1 { get; set; }
        public string Barcode2 { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> RetailPrice { get; set; }
        public Nullable<decimal> WholeSalesPrice { get; set; }
        public string DesignName { get; set; }
        public string Name { get; set; }
        public string ColorName { get; set; }
        public string DesignCode { get; set; }
        public string ProductName { get; set; }
        public string Code { get; set; }
        public string ProductInfo1 { get; set; }
        public int Id { get; set; }
    }
}
