//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiceMill_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiveDetail
    {
        public int Id { get; set; }
        public int ReceiveMasterId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> WarehouseId { get; set; }
        public decimal TotalBale { get; set; }
        public int QtyInBale { get; set; }
        public decimal WeightInKG { get; set; }
        public decimal WeightType { get; set; }
        public decimal WeightInMon { get; set; }
        public decimal Amount { get; set; }
        public decimal TotalAmount { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ReceiveMaster ReceiveMaster { get; set; }
        public virtual WareHouse WareHouse { get; set; }
    }
}
