//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiceMill_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryPayment
    {
        public long Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> LedgerId { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Month { get; set; }
        public Nullable<decimal> SalaryAmount { get; set; }
        public Nullable<decimal> Bonus { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<decimal> LoanDeduction { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Narration { get; set; }
    }
}
