//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiceMill_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesOrder()
        {
            this.SalesMasters = new HashSet<SalesMaster>();
            this.TempSalesMasters = new HashSet<TempSalesMaster>();
        }
    
        public int Id { get; set; }
        public string SalesOrderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string OrderRecieveBy { get; set; }
        public int CustomerID { get; set; }
        public int ProductId { get; set; }
        public int BaleQty { get; set; }
        public decimal BaleWeight { get; set; }
        public decimal TotalQtyInKG { get; set; }
        public decimal Rate { get; set; }
        public decimal Amount { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<decimal> DeliveryQty { get; set; }
        public string TransportType { get; set; }
        public string TransportNo { get; set; }
        public Nullable<System.DateTime> PricingDate { get; set; }
        public string Notes { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedDate { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalesMaster> SalesMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempSalesMaster> TempSalesMasters { get; set; }
    }
}
