//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REX_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Screen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Screen()
        {
            this.RoleWiseScreenPermissions = new HashSet<RoleWiseScreenPermission>();
        }
    
        public string ScreenId { get; set; }
        public string ScreenName { get; set; }
        public string URL { get; set; }
        public string ParentScreenId { get; set; }
        public string IconName { get; set; }
        public string Manager { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> SetDate { get; set; }
        public string UserName { get; set; }
        public Nullable<int> OrderBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoleWiseScreenPermission> RoleWiseScreenPermissions { get; set; }
    }
}
