//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RiceMill_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempSalesMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TempSalesMaster()
        {
            this.TempSalesDetails = new HashSet<TempSalesDetail>();
        }
    
        public int Id { get; set; }
        public string SalesInvoice { get; set; }
        public Nullable<int> SalesOrderId { get; set; }
        public Nullable<System.DateTime> SalesDate { get; set; }
        public string SalesBy { get; set; }
        public int CustomerID { get; set; }
        public decimal AdditionalCost { get; set; }
        public decimal Discount { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal GrandTotal { get; set; }
        public string TransportType { get; set; }
        public string TransportNo { get; set; }
        public Nullable<System.DateTime> PricingDate { get; set; }
        public string DiscountPurpose { get; set; }
        public string Notes { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedDate { get; set; }
        public bool IsActive { get; set; }
        public string Coutha { get; set; }
        public string DriverName { get; set; }
        public Nullable<decimal> RentAmount { get; set; }
        public Nullable<int> YearId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual SalesOrder SalesOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TempSalesDetail> TempSalesDetails { get; set; }
        public virtual TempSalesMaster TempSalesMaster1 { get; set; }
        public virtual TempSalesMaster TempSalesMaster2 { get; set; }
    }
}
